name: Test

on: [pull_request]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
      fail-fast: false
    steps:
      - name: Checkout p9fs
        uses: actions/checkout@v4

      - name: Checkout rust-9p
        uses: actions/checkout@v4
        with:
          repository: pfpacket/rust-9p

      - name: Run tests
        run: |
          pwd
          ls -l
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[tests]

      - name: Run tests
        run: ./scripts/test.sh

