name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
      fail-fast: false
    steps:
      - name: Checkout p9fs
        uses: actions/checkout@v4

      - name: Checkout rust-9p
        uses: actions/checkout@v4
        with:
          repository: pfpacket/rust-9p
          path: rust-9p

      - name: Build unpfs
        run: |
          cd rust-9p/example/unpfs/
          cargo build --release
          mkdir -p ~/.local/bin
          ln -s $PWD/target/release/unpfs ~/.local/bin

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install diod
        run: |
          sudo apt update -y
          sudo apt install -y diod 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[tests]

      - name: Run tests
        run: ./scripts/test.sh

      - name: Run tests for diod
        run: sudo ./scripts/test.sh --diod
